package model

type Feature struct {
	ID        uint   `json:"id" gorm:"column:id;primary_key;autoincrement"`
	ParentID  uint   `json:"parent_id" gorm:"column:parent_id"`
	Title     string `json:"title" gorm:"column:title"`
	Path      string `json:"path" gorm:"column:path"`
	MenuOrder uint   `json:"menu_order" gorm:"column:menu_order"`
	Status    uint   `json:"status" gorm:"column:status"`
	Level     uint   `json:"level" gorm:"column:level"`
	Icon      string `json:"icon" gorm:"column:icon"`
}

func (Feature) TableName() string {
	return "features"
}

var FEATURES = []Feature{
	{
		ID:        1,
		ParentID:  0,
		Title:     "Admin Dashboards",
		Path:      "tab-dashboards",
		MenuOrder: 1,
		Status:    1,
		Level:     0,
		Icon:      "bx-home-circle",
	},
	{
		ID:        2,
		ParentID:  0,
		Title:     "System User & Roles",
		Path:      "tab-roles",
		MenuOrder: 2,
		Status:    1,
		Level:     0,
		Icon:      "bx bx-group",
	},
	{
		ID:        3,
		ParentID:  0,
		Title:     "Warning",
		Path:      "tab-warning",
		MenuOrder: 3,
		Status:    1,
		Level:     0,
		Icon:      "bx bxs-bell-ring bx-tada-hover",
	},
	{
		ID:        4,
		ParentID:  0,
		Title:     "System Users",
		Path:      "tab-user-list",
		MenuOrder: 4,
		Status:    1,
		Level:     1,
		Icon:      "bx bx-user",
	},
	{
		ID:        5,
		ParentID:  0,
		Title:     "System Log",
		Path:      "tab-system-log",
		MenuOrder: 5,
		Status:    1,
		Level:     0,
		Icon:      "bx bx-terminal",
	},
	{
		ID:        6,
		ParentID:  0,
		Title:     "Log Activity",
		Path:      "tab-activity-log",
		MenuOrder: 6,
		Status:    1,
		Level:     0,
		Icon:      "bx bx-universal-access",
	},
	{
		ID:        7,
		ParentID:  0,
		Title:     "Merchant Settle Log",
		Path:      "tab-settlement-log",
		MenuOrder: 7,
		Status:    1,
		Level:     0,
		Icon:      "bx bx-swap-horizontal",
	},
	{
		ID:        8,
		ParentID:  0,
		Title:     "Issuer Log",
		Path:      "tab-issuer-log",
		MenuOrder: 8,
		Status:    1,
		Level:     0,
		Icon:      "bx bx-receipt",
	},
	{
		ID:        9,
		ParentID:  0,
		Title:     "Active Transactions",
		Path:      "tab-transaction",
		MenuOrder: 9,
		Status:    1,
		Level:     0,
		Icon:      "bx bx-currency-note",
	},
	{
		ID:        10,
		ParentID:  0,
		Title:     "Transactions Logs",
		Path:      "tab-transaction-log",
		MenuOrder: 10,
		Status:    1,
		Level:     0,
		Icon:      "bx bx-currency-notes",
	},
	{
		ID:        11,
		ParentID:  0,
		Title:     "All Merchants",
		Path:      "tab-all-merchants",
		MenuOrder: 11,
		Status:    1,
		Level:     0,
		Icon:      "bx bx-store-alt",
	},
	{
		ID:        12,
		ParentID:  0,
		Title:     "Merchant Management",
		Path:      "tab-merchant-management",
		MenuOrder: 12,
		Status:    1,
		Level:     0,
		Icon:      "bx bx-store-alt",
	},
	{
		ID:        13,
		ParentID:  0,
		Title:     "Terminate Merchant Contract",
		Path:      "tab-terminate-merchant-contract",
		MenuOrder: 13,
		Status:    1,
		Level:     0,
		Icon:      "bx bx-user-x",
	},
	{
		ID:        14,
		ParentID:  0,
		Title:     "All Terminals",
		Path:      "tab-all-terminals",
		MenuOrder: 14,
		Status:    1,
		Level:     0,
		Icon:      "bx bx-sitemap",
	},
	{
		ID:        14,
		ParentID:  0,
		Title:     "Manual Settlement",
		Path:      "tab-manual-settlement",
		MenuOrder: 14,
		Status:    1,
		Level:     0,
		Icon:      "bx bxs-user-voice",
	},
	{
		ID:        16,
		ParentID:  0,
		Title:     "System Parameters",
		Path:      "tab-parameters",
		MenuOrder: 16,
		Status:    1,
		Level:     0,
		Icon:      "bx bx-info-circle",
	},
	{
		ID:        17,
		ParentID:  0,
		Title:     "Monitoring FDS",
		Path:      "tab-suspect-list",
		MenuOrder: 17,
		Status:    1,
		Level:     0,
		Icon:      "bx bx-info-circle",
	},
	{
		ID:        18,
		ParentID:  0,
		Title:     "System Settings",
		Path:      "tab-settings",
		MenuOrder: 18,
		Status:    1,
		Level:     0,
		Icon:      "bx bx-cog",
	},
	{
		ID:        19,
		ParentID:  0,
		Title:     "User Profile",
		Path:      "tab-user-profile",
		MenuOrder: 19,
		Status:    1,
		Level:     0,
		Icon:      "bx bx-user-circle",
	},
	{
		ID:        20,
		ParentID:  0,
		Title:     "WhatsApp Admin",
		Path:      "tab-whatsapp-admin",
		MenuOrder: 20,
		Status:    1,
		Level:     0,
		Icon:      "bi bi-whatsapp",
	},
}
