// Code generated by generate-authenticated-routes.js - DO NOT EDIT
// Generated at: 2025-11-09T02:18:52.041Z

package helper

// AuthenticatedFileRoutes contains all authenticated route paths
// These routes require user authentication to access
var AuthenticatedFileRoutes = []string{
	"/",
	"/apps",
	"/chats",
	"/errors/$error",
	"/help-center",
	"/settings",
	"/settings/account",
	"/settings/appearance",
	"/settings/display",
	"/settings/notifications",
	"/tasks",
	"/users",
}

// IsAuthenticatedRoute checks if a path is an authenticated route
func IsAuthenticatedRoute(path string) bool {
	for _, route := range AuthenticatedFileRoutes {
		if route == path {
			return true
		}
	}
	return false
}
