package modelOdoo

import (
	"database/sql"
)

type ResPartner struct {
	ID                       int             `gorm:"column:id;primaryKey" json:"id"`
	CompanyID                sql.NullInt64   `gorm:"column:company_id" json:"company_id"`
	CreateDate               sql.NullTime    `gorm:"column:create_date" json:"create_date"`
	Name                     string          `gorm:"column:name" json:"name"`
	Title                    sql.NullInt64   `gorm:"column:title" json:"title"`
	ParentID                 sql.NullInt64   `gorm:"column:parent_id" json:"parent_id"`
	UserID                   sql.NullInt64   `gorm:"column:user_id" json:"user_id"`
	StateID                  sql.NullInt64   `gorm:"column:state_id" json:"state_id"`
	CountryID                sql.NullInt64   `gorm:"column:country_id" json:"country_id"`
	IndustryID               sql.NullInt64   `gorm:"column:industry_id" json:"industry_id"`
	Color                    sql.NullInt64   `gorm:"column:color" json:"color"`
	CommercialPartnerID      sql.NullInt64   `gorm:"column:commercial_partner_id" json:"commercial_partner_id"`
	CreateUID                sql.NullInt64   `gorm:"column:create_uid" json:"create_uid"`
	WriteUID                 sql.NullInt64   `gorm:"column:write_uid" json:"write_uid"`
	CompleteName             string          `gorm:"column:complete_name" json:"complete_name"`
	Ref                      string          `gorm:"column:ref" json:"ref"`
	Lang                     string          `gorm:"column:lang" json:"lang"`
	Tz                       string          `gorm:"column:tz" json:"tz"`
	VAT                      string          `gorm:"column:vat" json:"vat"`
	CompanyRegistry          string          `gorm:"column:company_registry" json:"company_registry"`
	Website                  string          `gorm:"column:website" json:"website"`
	Function                 string          `gorm:"column:function" json:"function"`
	Type                     string          `gorm:"column:type" json:"type"`
	Street                   string          `gorm:"column:street" json:"street"`
	Street2                  string          `gorm:"column:street2" json:"street2"`
	Zip                      string          `gorm:"column:zip" json:"zip"`
	City                     string          `gorm:"column:city" json:"city"`
	Email                    string          `gorm:"column:email" json:"email"`
	Phone                    string          `gorm:"column:phone" json:"phone"`
	Mobile                   string          `gorm:"column:mobile" json:"mobile"`
	CommercialCompanyName    string          `gorm:"column:commercial_company_name" json:"commercial_company_name"`
	CompanyName              string          `gorm:"column:company_name" json:"company_name"`
	Date                     sql.NullTime    `gorm:"column:date" json:"date"`
	Comment                  string          `gorm:"column:comment" json:"comment"`
	PartnerLatitude          sql.NullFloat64 `gorm:"column:partner_latitude" json:"partner_latitude"`
	PartnerLongitude         sql.NullFloat64 `gorm:"column:partner_longitude" json:"partner_longitude"`
	Active                   sql.NullBool    `gorm:"column:active" json:"active"`
	Employee                 sql.NullBool    `gorm:"column:employee" json:"employee"`
	IsCompany                sql.NullBool    `gorm:"column:is_company" json:"is_company"`
	PartnerShare             sql.NullBool    `gorm:"column:partner_share" json:"partner_share"`
	WriteDate                sql.NullTime    `gorm:"column:write_date" json:"write_date"`
	MessageBounce            sql.NullInt64   `gorm:"column:message_bounce" json:"message_bounce"`
	EmailNormalized          string          `gorm:"column:email_normalized" json:"email_normalized"`
	SignupType               string          `gorm:"column:signup_type" json:"signup_type"`
	SignupExpiration         sql.NullTime    `gorm:"column:signup_expiration" json:"signup_expiration"`
	SignupToken              string          `gorm:"column:signup_token" json:"signup_token"`
	TeamID                   sql.NullInt64   `gorm:"column:team_id" json:"team_id"`
	PartnerGID               sql.NullInt64   `gorm:"column:partner_gid" json:"partner_gid"`
	AdditionalInfo           string          `gorm:"column:additional_info" json:"additional_info"`
	PhoneSanitized           string          `gorm:"column:phone_sanitized" json:"phone_sanitized"`
	SupplierRank             sql.NullInt64   `gorm:"column:supplier_rank" json:"supplier_rank"`
	CustomerRank             sql.NullInt64   `gorm:"column:customer_rank" json:"customer_rank"`
	InvoiceWarn              string          `gorm:"column:invoice_warn" json:"invoice_warn"`
	InvoiceWarnMsg           string          `gorm:"column:invoice_warn_msg" json:"invoice_warn_msg"`
	DebitLimit               sql.NullFloat64 `gorm:"column:debit_limit" json:"debit_limit"`
	LastTimeEntriesChecked   sql.NullTime    `gorm:"column:last_time_entries_checked" json:"last_time_entries_checked"`
	WebsiteID                sql.NullInt64   `gorm:"column:website_id" json:"website_id"`
	IsPublished              sql.NullBool    `gorm:"column:is_published" json:"is_published"`
	UBL_CIIFormat            string          `gorm:"column:ubl_cii_format" json:"ubl_cii_format"`
	PeppolEndpoint           string          `gorm:"column:peppol_endpoint" json:"peppol_endpoint"`
	PeppolEAS                string          `gorm:"column:peppol_eas" json:"peppol_eas"`
	SaleWarn                 string          `gorm:"column:sale_warn" json:"sale_warn"`
	SaleWarnMsg              string          `gorm:"column:sale_warn_msg" json:"sale_warn_msg"`
	VIESValid                sql.NullBool    `gorm:"column:vies_valid" json:"vies_valid"`
	L10nIdNIK                string          `gorm:"column:l10n_id_nik" json:"l10n_id_nik"`
	L10nIdTaxAddress         string          `gorm:"column:l10n_id_tax_address" json:"l10n_id_tax_address"`
	L10nIdTaxName            string          `gorm:"column:l10n_id_tax_name" json:"l10n_id_tax_name"`
	L10nIdKodeTransaksi      string          `gorm:"column:l10n_id_kode_transaksi" json:"l10n_id_kode_transaksi"`
	L10nIdPKP                sql.NullBool    `gorm:"column:l10n_id_pkp" json:"l10n_id_pkp"`
	L10nIdTKU                string          `gorm:"column:l10n_id_tku" json:"l10n_id_tku"`
	L10nIdBuyerDocType       string          `gorm:"column:l10n_id_buyer_document_type" json:"l10n_id_buyer_document_type"`
	L10nIdBuyerDocNumber     string          `gorm:"column:l10n_id_buyer_document_number" json:"l10n_id_buyer_document_number"`
	PickingWarn              string          `gorm:"column:picking_warn" json:"picking_warn"`
	PickingWarnMsg           string          `gorm:"column:picking_warn_msg" json:"picking_warn_msg"`
	BuyerID                  sql.NullInt64   `gorm:"column:buyer_id" json:"buyer_id"`
	PurchaseWarn             string          `gorm:"column:purchase_warn" json:"purchase_warn"`
	PurchaseWarnMsg          string          `gorm:"column:purchase_warn_msg" json:"purchase_warn_msg"`
	ParentPartnerID          sql.NullInt64   `gorm:"column:parent_partner_id" json:"parent_partner_id"`
	TID                      string          `gorm:"column:tid" json:"tid"`
	MIDTID                   string          `gorm:"column:midtid" json:"midtid"`
	ShopName                 string          `gorm:"column:shop_name" json:"shop_name"`
	GroupName                string          `gorm:"column:group_name" json:"group_name"`
	MainBranch               sql.NullBool    `gorm:"column:main_branch" json:"main_branch"`
	IIDStoreID               sql.NullInt64   `gorm:"column:iid_store_id" json:"iid_store_id"`
	BankID                   sql.NullInt64   `gorm:"column:bank_id" json:"bank_id"`
	MembershipID             sql.NullInt64   `gorm:"column:membership_id" json:"membership_id"`
	AccHolderNumber          string          `gorm:"column:acc_holder_number" json:"acc_holder_number"`
	AccHolderName            string          `gorm:"column:acc_holder_name" json:"acc_holder_name"`
	TIN                      string          `gorm:"column:tin" json:"tin"`
	SubscriptionType         string          `gorm:"column:subscription_type" json:"subscription_type"`
	DataAgent                string          `gorm:"column:data_agent" json:"data_agent"`
	MID                      string          `gorm:"column:mid" json:"mid"`
	Agent                    string          `gorm:"column:agent" json:"agent"`
	FotoLokasiUsahaDepan     string          `gorm:"column:foto_lokasi_usaha_depan" json:"foto_lokasi_usaha_depan"`
	FotoLokasiUsahaBelakang  string          `gorm:"column:foto_lokasi_usaha_belakang" json:"foto_lokasi_usaha_belakang"`
	FotoLokasiUsahaProduksi  string          `gorm:"column:foto_lokasi_usaha_produksi" json:"foto_lokasi_usaha_produksi"`
	FotoLokasiUsahaStok      string          `gorm:"column:foto_lokasi_usaha_stok" json:"foto_lokasi_usaha_stok"`
	FotoKTP                  string          `gorm:"column:foto_ktp" json:"foto_ktp"`
	FotoTTD                  string          `gorm:"column:foto_ttd" json:"foto_ttd"`
	PartnerName              string          `gorm:"column:partner_name" json:"partner_name"`
	MembershipExpiryDate     sql.NullTime    `gorm:"column:membership_expiry_date" json:"membership_expiry_date"`
	BankOther                string          `gorm:"column:bank_other" json:"bank_other"`
	XBusinessName            string          `gorm:"column:x_business_name" json:"x_business_name"`
	XBusinessType            string          `gorm:"column:x_business_type" json:"x_business_type"`
	XRT                      string          `gorm:"column:x_rt" json:"x_rt"`
	XRW                      string          `gorm:"column:x_rw" json:"x_rw"`
	XKelurahan               string          `gorm:"column:x_kelurahan" json:"x_kelurahan"`
	XKecamatan               string          `gorm:"column:x_kecamatan" json:"x_kecamatan"`
	XBusinessCategory        string          `gorm:"column:x_business_category" json:"x_business_category"`
	XBusinessCategoryRisk    string          `gorm:"column:x_business_category_risk" json:"x_business_category_risk"`
	XPhysicalStore           string          `gorm:"column:x_physical_store" json:"x_physical_store"`
	XSerialNumber            string          `gorm:"column:x_serial_number" json:"x_serial_number"`
	XMPAN                    string          `gorm:"column:x_mpan" json:"x_mpan"`
	XNmid                    string          `gorm:"column:x_nmid" json:"x_nmid"`
	XQrisType                string          `gorm:"column:x_qris_type" json:"x_qris_type"`
	CalendarLastNotifAck     sql.NullTime    `gorm:"column:calendar_last_notif_ack" json:"calendar_last_notif_ack"`
	XBusinessDocCompleteness string          `gorm:"column:x_business_document_completeness" json:"x_business_document_completeness"`
	XBufferBank              string          `gorm:"column:x_buffer_bank" json:"x_buffer_bank"`
	CurrencyID               sql.NullInt64   `gorm:"column:currency_id" json:"currency_id"`
	VerifiedDatetime         sql.NullTime    `gorm:"column:verified_datetime" json:"verified_datetime"`
	BusinessLevel            string          `gorm:"column:business_level" json:"business_level"`
	MinBalance               sql.NullFloat64 `gorm:"column:min_balance" json:"min_balance"`
	TokenNotif               string          `gorm:"column:token_notif" json:"token_notif"`
}

func (ResPartner) TableName() string {
	return "res_partner"
}
