package modelMerchant

import (
	"time"

	"gorm.io/gorm"
)

type Bank struct {
	ID        uint `gorm:"primarykey"`
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt gorm.DeletedAt `gorm:"index"`
	BankCode  string         `gorm:"column:bank_code" json:"bank_code"`
	BankName  string         `gorm:"column:bank_name" json:"bank_name"`
}

func (Bank) TableName() string {
	return "banks"
}

var BANKS = []Bank{
	{BankName: "Bank BRI", BankCode: "002"},
	{BankName: "Bank Mandiri", BankCode: "008"},
	{BankName: "Bank BNI", BankCode: "009"},
	{BankName: "Bank BTN", BankCode: "200"},
	{BankName: "Bank BJB", BankCode: "110"},
	{BankName: "Bank DKI", BankCode: "111"},
	{BankName: "Bank BPD D.I.Y", BankCode: "112"},
	{BankName: "Bank Jateng", BankCode: "113"},
	{BankName: "Bank Jatim", BankCode: "114"},
	{BankName: "Bank Jambi", BankCode: "115"},
	{BankName: "Bank Aceh", BankCode: "116"},
	{BankName: "Bank Sumut", BankCode: "117"},
	{BankName: "Bank Sumbar", BankCode: "118"},
	{BankName: "Bank Kepri", BankCode: "119"},
	{BankName: "Bank Sumsel dan Babel", BankCode: "120"},
	{BankName: "Bank Lampung", BankCode: "121"},
	{BankName: "Bank kalsel", BankCode: "122"},
	{BankName: "Bank Kalbar", BankCode: "123"},
	{BankName: "Bank Kaltim", BankCode: "124"},
	{BankName: "Bank Kalteng", BankCode: "125"},
	{BankName: "Bank Sulsel", BankCode: "126"},
	{BankName: "Bank Sulut", BankCode: "127"},
	{BankName: "Bank Ntb", BankCode: "128"},
	{BankName: "Bank Bali", BankCode: "129"},
	{BankName: "Bank Ntt", BankCode: "130"},
	{BankName: "Bank Maluku", BankCode: "131"},
	{BankName: "Bank Papua", BankCode: "132"},
	{BankName: "Bank Bengkulu", BankCode: "133"},
	{BankName: "Bank Sulteng", BankCode: "134"},
	{BankName: "Bank Sultra", BankCode: "135"},
	{BankName: "Bank Banten", BankCode: "137"},
	{BankName: "Bank Ekspor Indonesia", BankCode: "003"},
	{BankName: "Bank Danamon Indonesia", BankCode: "011"},
	{BankName: "Bank Permata", BankCode: "013"},
	{BankName: "Bank BCA", BankCode: "014"},
	{BankName: "Bank Maybank", BankCode: "016"},
	{BankName: "Bank Panin", BankCode: "019"},
	{BankName: "Bank Arta Niaga Kencana", BankCode: "020"},
	{BankName: "Bank CIMB Niaga", BankCode: "022"},
	{BankName: "Bank UOB Indonesia", BankCode: "023"},
	{BankName: "Bank Lippo", BankCode: "026"},
	{BankName: "Bank OCBC NISP", BankCode: "028"},
	{BankName: "Bank Multicor", BankCode: "036"},
	{BankName: "Bank Artha Graha", BankCode: "037"},
	{BankName: "Bank Pesona Perdania", BankCode: "047"},
	{BankName: "Bank ABN Amro", BankCode: "052"},
	{BankName: "Bank Keppel Tatlee Buana", BankCode: "053"},
	{BankName: "Bank BNP Paribas Indonesia", BankCode: "057"},
	{BankName: "Bank Woori Indonesia", BankCode: "068"},
	{BankName: "Bank Bumi Arta", BankCode: "076"},
	{BankName: "Bank Ekonomi", BankCode: "087"},
	{BankName: "Bank Haga", BankCode: "089"},
	{BankName: "Bank IFI", BankCode: "093"},
	{BankName: "Bank Century/Bank J Trust Indonesia", BankCode: "095"},
	{BankName: "Bank Mayapada", BankCode: "097"},
	{BankName: "Bank Nusantara Parahyangan", BankCode: "145"},
	{BankName: "Bank Swadesi", BankCode: "146"},
	{BankName: "Bank Mestika", BankCode: "151"},
	{BankName: "Bank Metro Express", BankCode: "152"},
	{BankName: "Bank Maspion", BankCode: "157"},
	{BankName: "Bank Hagakita", BankCode: "159"},
	{BankName: "Bank Ganesha", BankCode: "161"},
	{BankName: "Bank Windu Kentjana", BankCode: "162"},
	{BankName: "Bank ICBC Indonesia", BankCode: "164"},
	{BankName: "Bank Harmoni Internasional", BankCode: "166"},
	{BankName: "Bank QNB", BankCode: "167"},
	{BankName: "Bank Swaguna", BankCode: "405"},
	{BankName: "Bank Mega", BankCode: "426"},
	{BankName: "Bank Bukopin", BankCode: "441"},
	{BankName: "Bank Bisnis Internasional", BankCode: "459"},
	{BankName: "Bank Sri Partha", BankCode: "466"},
	{BankName: "Bank KEB Hana Indonesia", BankCode: "484"},
	{BankName: "Bank MNC Internasional", BankCode: "485"},
	{BankName: "Bank Neo", BankCode: "490"},
	{BankName: "Bank BNI Agro", BankCode: "494"},
	{BankName: "Bank Nobu", BankCode: "503"},
	{BankName: "Bank Ina Perdana", BankCode: "513"},
	{BankName: "Bank Sahabat Sampoerna", BankCode: "523"},
	{BankName: "SeaBank", BankCode: "535"},
	{BankName: "Bank Jago", BankCode: "542"},
	{BankName: "Bank Mayora", BankCode: "553"},
	{BankName: "Bank Index Selindo", BankCode: "555"},
	{BankName: "AlloBank", BankCode: "567"},
	{BankName: "Bank American Express Bank LTD", BankCode: "030"},
	{BankName: "Bank JP. Morgan Chase Bank, N.A", BankCode: "032"},
	{BankName: "Bank Citibank", BankCode: "031"},
	{BankName: "Bank of America, N.A", BankCode: "033"},
	{BankName: "Bank ING Indonesia Bank", BankCode: "034"},
	{BankName: "Bank China Construction Bank Indonesia", BankCode: "036"},
	{BankName: "Bank Credit Agricole Indosuez", BankCode: "039"},
	{BankName: "Bank Bangkok", BankCode: "040"},
	{BankName: "Bank of Tokyo Mitsubishi", BankCode: "042"},
	{BankName: "Bank Sumitomo Mitsui Indonesia", BankCode: "045"},
	{BankName: "Bank DBS Indonesia", BankCode: "046"},
	{BankName: "Bank Mihuzo Indonesia", BankCode: "048"},
	{BankName: "Bank Standard Chartered", BankCode: "050"},
	{BankName: "Bank Capital Indonesia", BankCode: "054"},
	{BankName: "Bank ANZ Indonesia", BankCode: "061"},
	{BankName: "Bank of China Indonesia", BankCode: "069"},
	{BankName: "Bank Deutsche", BankCode: "067"},
	{BankName: "Bank Shinhan Indonesia", BankCode: "152"},
	{BankName: "Bank Woori Saudara Indonesia", BankCode: "212"},
	{BankName: "Bank Commonwealth", BankCode: "950"},
	{BankName: "Bank CIMB Niaga Syariah", BankCode: "022"},
	{BankName: "Bank Muamalat", BankCode: "147"},
	{BankName: "Bank BJB Syariah", BankCode: "425"},
	{BankName: "Bank Syariah Indonesia ( BSI )", BankCode: "451"},
	{BankName: "Bank Mega Syariah", BankCode: "506"},
	{BankName: "Bank Panin Dubai Syariah", BankCode: "517"},
	{BankName: "Bank Bukopin Syariah", BankCode: "521"},
	{BankName: "Bank BCA Syariah", BankCode: "536"},
	{BankName: "Bank BTPN Syariah", BankCode: "547"},
	{BankName: "Bank Aladin Syariah", BankCode: "947"},
}
