/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as EditorThemeRouteRouteImport } from './routes/editor/theme/route'
import { Route as DashboardAuthenticatedRouteRouteImport } from './routes/dashboard/_authenticated/route'
import { Route as EditorThemeIndexRouteImport } from './routes/editor/theme/index'
import { Route as DashboardAuthenticatedIndexRouteImport } from './routes/dashboard/_authenticated/index'
import { Route as DashboardAuthenticatedSettingsRouteRouteImport } from './routes/dashboard/_authenticated/settings/route'
import { Route as DashboardAuthenticatedUsersIndexRouteImport } from './routes/dashboard/_authenticated/users/index'
import { Route as DashboardAuthenticatedTasksIndexRouteImport } from './routes/dashboard/_authenticated/tasks/index'
import { Route as DashboardAuthenticatedSettingsIndexRouteImport } from './routes/dashboard/_authenticated/settings/index'
import { Route as DashboardAuthenticatedHelpCenterIndexRouteImport } from './routes/dashboard/_authenticated/help-center/index'
import { Route as DashboardAuthenticatedChatsIndexRouteImport } from './routes/dashboard/_authenticated/chats/index'
import { Route as DashboardAuthenticatedAppsIndexRouteImport } from './routes/dashboard/_authenticated/apps/index'
import { Route as DashboardAuthenticatedSettingsNotificationsRouteImport } from './routes/dashboard/_authenticated/settings/notifications'
import { Route as DashboardAuthenticatedSettingsDisplayRouteImport } from './routes/dashboard/_authenticated/settings/display'
import { Route as DashboardAuthenticatedSettingsAppearanceRouteImport } from './routes/dashboard/_authenticated/settings/appearance'
import { Route as DashboardAuthenticatedSettingsAccountRouteImport } from './routes/dashboard/_authenticated/settings/account'
import { Route as DashboardAuthenticatedErrorsErrorRouteImport } from './routes/dashboard/_authenticated/errors/$error'

const DashboardRouteImport = createFileRoute('/dashboard')()

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authRouteRoute,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authRouteRoute,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)
const EditorThemeRouteRoute = EditorThemeRouteRouteImport.update({
  id: '/editor/theme',
  path: '/editor/theme',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAuthenticatedRouteRoute =
  DashboardAuthenticatedRouteRouteImport.update({
    id: '/_authenticated',
    getParentRoute: () => DashboardRoute,
  } as any)
const EditorThemeIndexRoute = EditorThemeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EditorThemeRouteRoute,
} as any)
const DashboardAuthenticatedIndexRoute =
  DashboardAuthenticatedIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardAuthenticatedRouteRoute,
  } as any)
const DashboardAuthenticatedSettingsRouteRoute =
  DashboardAuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardAuthenticatedRouteRoute,
  } as any)
const DashboardAuthenticatedUsersIndexRoute =
  DashboardAuthenticatedUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => DashboardAuthenticatedRouteRoute,
  } as any)
const DashboardAuthenticatedTasksIndexRoute =
  DashboardAuthenticatedTasksIndexRouteImport.update({
    id: '/tasks/',
    path: '/tasks/',
    getParentRoute: () => DashboardAuthenticatedRouteRoute,
  } as any)
const DashboardAuthenticatedSettingsIndexRoute =
  DashboardAuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardAuthenticatedSettingsRouteRoute,
  } as any)
const DashboardAuthenticatedHelpCenterIndexRoute =
  DashboardAuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => DashboardAuthenticatedRouteRoute,
  } as any)
const DashboardAuthenticatedChatsIndexRoute =
  DashboardAuthenticatedChatsIndexRouteImport.update({
    id: '/chats/',
    path: '/chats/',
    getParentRoute: () => DashboardAuthenticatedRouteRoute,
  } as any)
const DashboardAuthenticatedAppsIndexRoute =
  DashboardAuthenticatedAppsIndexRouteImport.update({
    id: '/apps/',
    path: '/apps/',
    getParentRoute: () => DashboardAuthenticatedRouteRoute,
  } as any)
const DashboardAuthenticatedSettingsNotificationsRoute =
  DashboardAuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => DashboardAuthenticatedSettingsRouteRoute,
  } as any)
const DashboardAuthenticatedSettingsDisplayRoute =
  DashboardAuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => DashboardAuthenticatedSettingsRouteRoute,
  } as any)
const DashboardAuthenticatedSettingsAppearanceRoute =
  DashboardAuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => DashboardAuthenticatedSettingsRouteRoute,
  } as any)
const DashboardAuthenticatedSettingsAccountRoute =
  DashboardAuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => DashboardAuthenticatedSettingsRouteRoute,
  } as any)
const DashboardAuthenticatedErrorsErrorRoute =
  DashboardAuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => DashboardAuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardAuthenticatedRouteRouteWithChildren
  '/editor/theme': typeof EditorThemeRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/otp': typeof authOtpRoute
  '/register': typeof authRegisterRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/dashboard/settings': typeof DashboardAuthenticatedSettingsRouteRouteWithChildren
  '/dashboard/': typeof DashboardAuthenticatedIndexRoute
  '/editor/theme/': typeof EditorThemeIndexRoute
  '/dashboard/errors/$error': typeof DashboardAuthenticatedErrorsErrorRoute
  '/dashboard/settings/account': typeof DashboardAuthenticatedSettingsAccountRoute
  '/dashboard/settings/appearance': typeof DashboardAuthenticatedSettingsAppearanceRoute
  '/dashboard/settings/display': typeof DashboardAuthenticatedSettingsDisplayRoute
  '/dashboard/settings/notifications': typeof DashboardAuthenticatedSettingsNotificationsRoute
  '/dashboard/apps': typeof DashboardAuthenticatedAppsIndexRoute
  '/dashboard/chats': typeof DashboardAuthenticatedChatsIndexRoute
  '/dashboard/help-center': typeof DashboardAuthenticatedHelpCenterIndexRoute
  '/dashboard/settings/': typeof DashboardAuthenticatedSettingsIndexRoute
  '/dashboard/tasks': typeof DashboardAuthenticatedTasksIndexRoute
  '/dashboard/users': typeof DashboardAuthenticatedUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardAuthenticatedIndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/otp': typeof authOtpRoute
  '/register': typeof authRegisterRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/editor/theme': typeof EditorThemeIndexRoute
  '/dashboard/errors/$error': typeof DashboardAuthenticatedErrorsErrorRoute
  '/dashboard/settings/account': typeof DashboardAuthenticatedSettingsAccountRoute
  '/dashboard/settings/appearance': typeof DashboardAuthenticatedSettingsAppearanceRoute
  '/dashboard/settings/display': typeof DashboardAuthenticatedSettingsDisplayRoute
  '/dashboard/settings/notifications': typeof DashboardAuthenticatedSettingsNotificationsRoute
  '/dashboard/apps': typeof DashboardAuthenticatedAppsIndexRoute
  '/dashboard/chats': typeof DashboardAuthenticatedChatsIndexRoute
  '/dashboard/help-center': typeof DashboardAuthenticatedHelpCenterIndexRoute
  '/dashboard/settings': typeof DashboardAuthenticatedSettingsIndexRoute
  '/dashboard/tasks': typeof DashboardAuthenticatedTasksIndexRoute
  '/dashboard/users': typeof DashboardAuthenticatedUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/_authenticated': typeof DashboardAuthenticatedRouteRouteWithChildren
  '/editor/theme': typeof EditorThemeRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/dashboard/_authenticated/settings': typeof DashboardAuthenticatedSettingsRouteRouteWithChildren
  '/dashboard/_authenticated/': typeof DashboardAuthenticatedIndexRoute
  '/editor/theme/': typeof EditorThemeIndexRoute
  '/dashboard/_authenticated/errors/$error': typeof DashboardAuthenticatedErrorsErrorRoute
  '/dashboard/_authenticated/settings/account': typeof DashboardAuthenticatedSettingsAccountRoute
  '/dashboard/_authenticated/settings/appearance': typeof DashboardAuthenticatedSettingsAppearanceRoute
  '/dashboard/_authenticated/settings/display': typeof DashboardAuthenticatedSettingsDisplayRoute
  '/dashboard/_authenticated/settings/notifications': typeof DashboardAuthenticatedSettingsNotificationsRoute
  '/dashboard/_authenticated/apps/': typeof DashboardAuthenticatedAppsIndexRoute
  '/dashboard/_authenticated/chats/': typeof DashboardAuthenticatedChatsIndexRoute
  '/dashboard/_authenticated/help-center/': typeof DashboardAuthenticatedHelpCenterIndexRoute
  '/dashboard/_authenticated/settings/': typeof DashboardAuthenticatedSettingsIndexRoute
  '/dashboard/_authenticated/tasks/': typeof DashboardAuthenticatedTasksIndexRoute
  '/dashboard/_authenticated/users/': typeof DashboardAuthenticatedUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/editor/theme'
    | '/forgot-password'
    | '/login'
    | '/otp'
    | '/register'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/editor/theme/'
    | '/dashboard/errors/$error'
    | '/dashboard/settings/account'
    | '/dashboard/settings/appearance'
    | '/dashboard/settings/display'
    | '/dashboard/settings/notifications'
    | '/dashboard/apps'
    | '/dashboard/chats'
    | '/dashboard/help-center'
    | '/dashboard/settings/'
    | '/dashboard/tasks'
    | '/dashboard/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/otp'
    | '/register'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/editor/theme'
    | '/dashboard/errors/$error'
    | '/dashboard/settings/account'
    | '/dashboard/settings/appearance'
    | '/dashboard/settings/display'
    | '/dashboard/settings/notifications'
    | '/dashboard/apps'
    | '/dashboard/chats'
    | '/dashboard/help-center'
    | '/dashboard/settings'
    | '/dashboard/tasks'
    | '/dashboard/users'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/dashboard'
    | '/dashboard/_authenticated'
    | '/editor/theme'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/otp'
    | '/(auth)/register'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/dashboard/_authenticated/settings'
    | '/dashboard/_authenticated/'
    | '/editor/theme/'
    | '/dashboard/_authenticated/errors/$error'
    | '/dashboard/_authenticated/settings/account'
    | '/dashboard/_authenticated/settings/appearance'
    | '/dashboard/_authenticated/settings/display'
    | '/dashboard/_authenticated/settings/notifications'
    | '/dashboard/_authenticated/apps/'
    | '/dashboard/_authenticated/chats/'
    | '/dashboard/_authenticated/help-center/'
    | '/dashboard/_authenticated/settings/'
    | '/dashboard/_authenticated/tasks/'
    | '/dashboard/_authenticated/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  EditorThemeRouteRoute: typeof EditorThemeRouteRouteWithChildren
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/editor/theme': {
      id: '/editor/theme'
      path: '/editor/theme'
      fullPath: '/editor/theme'
      preLoaderRoute: typeof EditorThemeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_authenticated': {
      id: '/dashboard/_authenticated'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardAuthenticatedRouteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/editor/theme/': {
      id: '/editor/theme/'
      path: '/'
      fullPath: '/editor/theme/'
      preLoaderRoute: typeof EditorThemeIndexRouteImport
      parentRoute: typeof EditorThemeRouteRoute
    }
    '/dashboard/_authenticated/': {
      id: '/dashboard/_authenticated/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardAuthenticatedIndexRouteImport
      parentRoute: typeof DashboardAuthenticatedRouteRoute
    }
    '/dashboard/_authenticated/settings': {
      id: '/dashboard/_authenticated/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardAuthenticatedSettingsRouteRouteImport
      parentRoute: typeof DashboardAuthenticatedRouteRoute
    }
    '/dashboard/_authenticated/users/': {
      id: '/dashboard/_authenticated/users/'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardAuthenticatedUsersIndexRouteImport
      parentRoute: typeof DashboardAuthenticatedRouteRoute
    }
    '/dashboard/_authenticated/tasks/': {
      id: '/dashboard/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/dashboard/tasks'
      preLoaderRoute: typeof DashboardAuthenticatedTasksIndexRouteImport
      parentRoute: typeof DashboardAuthenticatedRouteRoute
    }
    '/dashboard/_authenticated/settings/': {
      id: '/dashboard/_authenticated/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardAuthenticatedSettingsIndexRouteImport
      parentRoute: typeof DashboardAuthenticatedSettingsRouteRoute
    }
    '/dashboard/_authenticated/help-center/': {
      id: '/dashboard/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/dashboard/help-center'
      preLoaderRoute: typeof DashboardAuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof DashboardAuthenticatedRouteRoute
    }
    '/dashboard/_authenticated/chats/': {
      id: '/dashboard/_authenticated/chats/'
      path: '/chats'
      fullPath: '/dashboard/chats'
      preLoaderRoute: typeof DashboardAuthenticatedChatsIndexRouteImport
      parentRoute: typeof DashboardAuthenticatedRouteRoute
    }
    '/dashboard/_authenticated/apps/': {
      id: '/dashboard/_authenticated/apps/'
      path: '/apps'
      fullPath: '/dashboard/apps'
      preLoaderRoute: typeof DashboardAuthenticatedAppsIndexRouteImport
      parentRoute: typeof DashboardAuthenticatedRouteRoute
    }
    '/dashboard/_authenticated/settings/notifications': {
      id: '/dashboard/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/dashboard/settings/notifications'
      preLoaderRoute: typeof DashboardAuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof DashboardAuthenticatedSettingsRouteRoute
    }
    '/dashboard/_authenticated/settings/display': {
      id: '/dashboard/_authenticated/settings/display'
      path: '/display'
      fullPath: '/dashboard/settings/display'
      preLoaderRoute: typeof DashboardAuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof DashboardAuthenticatedSettingsRouteRoute
    }
    '/dashboard/_authenticated/settings/appearance': {
      id: '/dashboard/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/dashboard/settings/appearance'
      preLoaderRoute: typeof DashboardAuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof DashboardAuthenticatedSettingsRouteRoute
    }
    '/dashboard/_authenticated/settings/account': {
      id: '/dashboard/_authenticated/settings/account'
      path: '/account'
      fullPath: '/dashboard/settings/account'
      preLoaderRoute: typeof DashboardAuthenticatedSettingsAccountRouteImport
      parentRoute: typeof DashboardAuthenticatedSettingsRouteRoute
    }
    '/dashboard/_authenticated/errors/$error': {
      id: '/dashboard/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/dashboard/errors/$error'
      preLoaderRoute: typeof DashboardAuthenticatedErrorsErrorRouteImport
      parentRoute: typeof DashboardAuthenticatedRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authOtpRoute: typeof authOtpRoute
  authRegisterRoute: typeof authRegisterRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authOtpRoute: authOtpRoute,
  authRegisterRoute: authRegisterRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface DashboardAuthenticatedSettingsRouteRouteChildren {
  DashboardAuthenticatedSettingsAccountRoute: typeof DashboardAuthenticatedSettingsAccountRoute
  DashboardAuthenticatedSettingsAppearanceRoute: typeof DashboardAuthenticatedSettingsAppearanceRoute
  DashboardAuthenticatedSettingsDisplayRoute: typeof DashboardAuthenticatedSettingsDisplayRoute
  DashboardAuthenticatedSettingsNotificationsRoute: typeof DashboardAuthenticatedSettingsNotificationsRoute
  DashboardAuthenticatedSettingsIndexRoute: typeof DashboardAuthenticatedSettingsIndexRoute
}

const DashboardAuthenticatedSettingsRouteRouteChildren: DashboardAuthenticatedSettingsRouteRouteChildren =
  {
    DashboardAuthenticatedSettingsAccountRoute:
      DashboardAuthenticatedSettingsAccountRoute,
    DashboardAuthenticatedSettingsAppearanceRoute:
      DashboardAuthenticatedSettingsAppearanceRoute,
    DashboardAuthenticatedSettingsDisplayRoute:
      DashboardAuthenticatedSettingsDisplayRoute,
    DashboardAuthenticatedSettingsNotificationsRoute:
      DashboardAuthenticatedSettingsNotificationsRoute,
    DashboardAuthenticatedSettingsIndexRoute:
      DashboardAuthenticatedSettingsIndexRoute,
  }

const DashboardAuthenticatedSettingsRouteRouteWithChildren =
  DashboardAuthenticatedSettingsRouteRoute._addFileChildren(
    DashboardAuthenticatedSettingsRouteRouteChildren,
  )

interface DashboardAuthenticatedRouteRouteChildren {
  DashboardAuthenticatedSettingsRouteRoute: typeof DashboardAuthenticatedSettingsRouteRouteWithChildren
  DashboardAuthenticatedIndexRoute: typeof DashboardAuthenticatedIndexRoute
  DashboardAuthenticatedErrorsErrorRoute: typeof DashboardAuthenticatedErrorsErrorRoute
  DashboardAuthenticatedAppsIndexRoute: typeof DashboardAuthenticatedAppsIndexRoute
  DashboardAuthenticatedChatsIndexRoute: typeof DashboardAuthenticatedChatsIndexRoute
  DashboardAuthenticatedHelpCenterIndexRoute: typeof DashboardAuthenticatedHelpCenterIndexRoute
  DashboardAuthenticatedTasksIndexRoute: typeof DashboardAuthenticatedTasksIndexRoute
  DashboardAuthenticatedUsersIndexRoute: typeof DashboardAuthenticatedUsersIndexRoute
}

const DashboardAuthenticatedRouteRouteChildren: DashboardAuthenticatedRouteRouteChildren =
  {
    DashboardAuthenticatedSettingsRouteRoute:
      DashboardAuthenticatedSettingsRouteRouteWithChildren,
    DashboardAuthenticatedIndexRoute: DashboardAuthenticatedIndexRoute,
    DashboardAuthenticatedErrorsErrorRoute:
      DashboardAuthenticatedErrorsErrorRoute,
    DashboardAuthenticatedAppsIndexRoute: DashboardAuthenticatedAppsIndexRoute,
    DashboardAuthenticatedChatsIndexRoute:
      DashboardAuthenticatedChatsIndexRoute,
    DashboardAuthenticatedHelpCenterIndexRoute:
      DashboardAuthenticatedHelpCenterIndexRoute,
    DashboardAuthenticatedTasksIndexRoute:
      DashboardAuthenticatedTasksIndexRoute,
    DashboardAuthenticatedUsersIndexRoute:
      DashboardAuthenticatedUsersIndexRoute,
  }

const DashboardAuthenticatedRouteRouteWithChildren =
  DashboardAuthenticatedRouteRoute._addFileChildren(
    DashboardAuthenticatedRouteRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardAuthenticatedRouteRoute: typeof DashboardAuthenticatedRouteRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAuthenticatedRouteRoute:
    DashboardAuthenticatedRouteRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface EditorThemeRouteRouteChildren {
  EditorThemeIndexRoute: typeof EditorThemeIndexRoute
}

const EditorThemeRouteRouteChildren: EditorThemeRouteRouteChildren = {
  EditorThemeIndexRoute: EditorThemeIndexRoute,
}

const EditorThemeRouteRouteWithChildren =
  EditorThemeRouteRoute._addFileChildren(EditorThemeRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  EditorThemeRouteRoute: EditorThemeRouteRouteWithChildren,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
